---
- hosts: test
  become: True
  tasks:
  
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present  

    - name: Install dependencies
      pip: name={{ item }} state=present
      with_items:
        - urlparser
        
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Start the container
      docker_container:
        name: alluredocker
        image: "frankescobar/allure-docker-service:latest"
        env:
            CHECK_RESULTS_EVERY_SECONDS: "NONE"
            KEEP_HISTORY: "1"
            KEEP_HISTORY_LATEST: "25"
        state: started
        volumes:
          - ${PWD}/projects:/app/projects       
        published_ports:
          - 0.0.0.0:5050:5050
