---
- hosts: test
  #become: True
  become_user: testadmin

  vars:
    allure_image_name: frankescobar/allure-docker-service:latest
    allure_container_name: alluredocker
    allure_project_path: /app/projects
    check_result_every_second: NONE
    keep_history_flag: "1"
    keep_history_latest: "30"
    external_port: "5050"
    internal_port: "5050"
    src_path: /opt/allure
    dest_path: ${PWD}/allure
    file: docker-compose.yml
  
  tasks:
    
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present  

    - name: Install dependencies
      pip: name={{ item }} state=present
      with_items:
        - urlparser
        - docker
        - docker-api
        - PyYAML
        - docker-compose
        - docker-py
        - urllib3
        - requests

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Allure docker image
      shell: docker pull {{allure_image_name}}

    - name: workspace location
      debug:
        msg: "workspace location is {{ src_path }}"
        
    - name: Copy files from jenkins server to remote server
      copy:
        remote_src: no
        src: "{{ src_path }}"
        dest: "{{ dest_path }}/{{ file }}"       

    - name: Check if docker-compose is installed
      shell: command -v docker-compose >/dev/null 2>&1
      register: is_docker_compose_install
      failed_when: is_docker_compose_install is not defined
      ignore_errors: yes

    - debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 0 if present

    # Creates the allure container defined by the variable
    - name: Spin up the allure docker container
      # become: True
      #command: docker-compose -f {{ dest_path }}/{{ file }} up -d allure allure-ui
      command: docker-compose up -d allure allure-ui
      args:
        chdir: '{{ dest_path }}/{{ file }}'
    #ignore_errors: true
