---
- hosts: test
  become: True

  vars:
    allure_image_name: frankescobar/allure-docker-service:latest
    allure_container_name: alluredocker
    allure_project_path: /app/projects
    check_result_every_second: NONE
    keep_history_flag: "1"
    keep_history_latest: "30"
    external_port: "5050"
    internal_port: "5050"
  
  tasks:
    
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present  

    - name: Install dependencies
      pip: name={{ item }} state=present
      with_items:
        - urlparser
        - docker
        - docker-api
        - PyYAML
        - docker-compose
        - docker-py
        
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Allure docker image
      shell: docker pull {{allure_image_name}}

    # Creates the allure container defined by the variable
    - name: Start the Allure container 
      community.general.docker_compose:
        project_name: allure-docker-service
        definition:
          version: '3'
          services:
            allure:
              image: "frankescobar/allure-docker-service:latest"
              environment:
                CHECK_RESULTS_EVERY_SECONDS: "{{ check_result_every_second }}"
                KEEP_HISTORY: "{{ keep_history_flag }}"
                KEEP_HISTORY_LATEST: "{{ keep_history_latest }}"              
              volumes:
                - ${PWD}/projects:"{{ allure_project_path }}"
              ports:
                - "5050:5050"
              depends_on:
                - db
      register: output
