---
- hosts: test
  become: True

  vars:
    allure_image_name: frankescobar/allure-docker-service:latest
    allure_container_name: alluredocker
    allure_project_path: /app/projects
    check_result_every_second: NONE
    keep_history_flag: "1"
    keep_history_latest: "30"
    external_port: "5050"
    internal_port: "5050"
    src_path: /opt/allure/docker-compose.yml
    dest_path: ${PWD}/allure
    file: docker-compose.yml
  
  tasks:
    
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present  

    - name: Install dependencies
      pip: name={{ item }} state=present
      with_items:
        - urlparser
        - docker
        - docker-api
        - PyYAML
        - docker-compose
        - docker-py
        - urllib3
        - requests

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Allure docker image
      shell: docker pull {{allure_image_name}}

    - name: Create target directory
      file:
        path: ${PWD}/allure
        state: directory
        owner: adm
        group: adm
        mode: 755
      register: path

    - name: Directory location
      debug:
        msg: "directory location is {{ path }}"        
        
    - name: workspace location
      debug:
        msg: "workspace location is {{ src_path }}"
        
    - name: Copy files from jenkins server to remote server
      copy:
        remote_src: true
        src: "{{ src_path }}"
        dest: "{{ dest_path }}//{{ file }}"
        mode: 755        

    # Creates the allure container defined by the variable
    - name: Spin up the allure docker container
      become: yes
      shell: docker-compose up -d allure allure-ui
      args:
        chdir: '{{ dest_path }}'
      ignore_errors: true
