---
- hosts: test
  become: True

  vars:
    allure_image_name: frankescobar/allure-docker-service:latest
    allure_container_name: alluredocker
    allure_project_path: /app/projects
    check_result_every_second: NONE
    keep_history_flag: "1"
    keep_history_latest: "30"
    external_port: "5050"
    internal_port: "5050"
  
  tasks:
    
    - name: Install docker-py python module
      pip3:
        name: docker-py
        state: present  

    - name: Install dependencies
      pip3: name={{ item }} state=present
      with_items:
        - urlparser
        - docker
        - docker-api
        - PyYAML
        - docker-compose
        - docker-py
        - urllib3
        - requests
        
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Allure docker image
      shell: docker pull {{allure_image_name}}

    # Creates the allure container defined by the variable
    - docker_service:
        project_src: src
        build: no
      register: output
